version: '2'

services:
    golang-edu:
        container_name: education-microservices
        build:
            context: .
            dockerfile: ./src/education-microservices/education.dockerfile
        networks: 
            - mgo-network
        ports:
            - '8082:8081'
    golang-exp:
        container_name: experience-microservices
        build:
            context: .
            dockerfile: ./src/experiences-microservices/experience.dockerfile
        networks: 
            - mgo-network
        ports:
            - '8081:8082'
    mongo-edu:
        image: mongo:4.0.2
        container_name: mongo-education
        networks: 
            - mgo-network
        ports: 
            - '27018:27017'
    mongo-exp:
        image: mongo:4.0.2
        container_name: mongo-experience
        networks: 
            - mgo-network
        ports: 
            - '27017:27017'
networks: 
    mgo-network:
        driver: bridge

        # docker-compose build  
        # docker-compose up -d  
        # docker-compose down  
        # docker-compose kill
        # docker-compose ps
        # docker-compose logs
            